name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👉 This line is what “ensures it builds with Node 18”
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci || npm install
      - run: npm run build   # will run: next build && next export

      # 👉 This step uploads the exported site from the `out` folder to Azure
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_PLANT_09679E603 }} # ← keep YOUR existing secret name
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "out"     # ← this is the folder produced by `next export`
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_PLANT_09679E603 }} # same secret name
          action: "close"

