name: Deploy to Azure Static Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: azure-static-website
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (works with or without lockfile)
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci (lockfile present)"
            npm ci
          else
            echo "No lockfile found — using npm install"
            npm install
          fi

      - name: Generate media JSON (audio/videos)
        run: |
          if [ -f scripts/generateMedia.cjs ]; then
            node scripts/generateMedia.cjs
          else
            echo "scripts/generateMedia.cjs not found — skipping generator."
          fi

      # With next.config.js { output: "export" }, this produces ./out
      - name: Build (Next.js static export)
        run: npm run build

      - name: Verify build output exists
        run: |
          test -d out && echo "✅ out/ exists" || (echo "❌ out/ not found"; exit 1)

      - name: Upload to Azure Static Website
        uses: azure/cli@v2
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        with:
          azcliversion: "2.61.0"
          inlineScript: |
            set -e

            if [ -n "$AZURE_STORAGE_CONNECTION_STRING" ]; then
              echo "Using connection string"
              az storage blob service-properties update \
                --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
                --static-website \
                --index-document index.html \
                --404-document 404.html

              az storage blob sync \
                --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
                -c '$web' \
                -s ./out \
                --delete-destination true

            elif [ -n "$AZURE_STORAGE_ACCOUNT" ] && [ -n "$AZURE_STORAGE_KEY" ]; then
              echo "Using account + key"
              az storage blob service-properties update \
                --account-name "$AZURE_STORAGE_ACCOUNT" \
                --account-key "$AZURE_STORAGE_KEY" \
                --static-website \
                --index-document index.html \
                --404-document 404.html

              az storage blob sync \
                --account-name "$AZURE_STORAGE_ACCOUNT" \
                --accou
