name: Deploy to Azure Storage Static Website
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install
      
      - name: Make public folder
        run: mkdir -p public

      - name: Fetch home hero
        run: curl -fsSL -o public/hero-home.jpg 'https://shadowsandlightmusic.com/wp-content/uploads/2015/12/featureimg012.jpg'

      - name: Copy about + contact hero (same art as home)
        run: cp public/hero-home.jpg public/hero-about.jpg && cp public/hero-home.jpg public/hero-contact.jpg

      - name: Fetch press hero
        run: curl -fsSL -o public/hero-press.jpg 'https://shadowsandlightmusic.com/wp-content/uploads/2015/12/featureimg041.jpg'

      - name: Fetch live photo
        run: curl -fsSL -o public/live.jpg 'https://shadowsandlightmusic.com/wp-content/uploads/2020/01/shadows-and-light-colour-naul-2018-hi-res.jpg'
      - name: Build (Next static export)
        run: npm run build

      - name: Verify out folder exists
        run: ls -la out || (echo "No out directory found" && exit 1)

      - name: Upload to $web
        uses: azure/cli@v2
        with:
          inlineScript: az storage blob upload-batch --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT }}" --destination '$web' --source ./out --sas-token "${{ secrets.AZURE_STORAGE_SAS }}" --overwrite
