name: Deploy to Azure Static Website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Optional: generate JSON (only if you added scripts/generateMedia.cjs)
      - name: Generate media JSON
        run: |
          if [ -f scripts/generateMedia.cjs ]; then
            node scripts/generateMedia.cjs
          else
            echo "No generator script found — skipping."
          fi

      # With next.config.js { output: 'export' }, this creates ./out
      - name: Build (Next.js static export)
        run: npm run build

      - name: Verify build output
        run: test -d out

      - name: Upload to Azure Static Website
        uses: azure/cli@v2
        env:
          # Provide ONE of these in repo Settings → Secrets and variables → Actions
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }} # no leading '?'
        with:
          azcliversion: "2.61.0"
          inlineScript: |
            set -euo pipefail
            # Azure CLI will pick credentials from env automatically.
            # Try enabling static website (skip errors e.g., when using SAS):
            az storage blob service-properties update \
              --static-website \
              --index-document index.html \
              --404-document 404.html || true

            # Sync build output to $web
            az storage blob sync \
              -c '$web' \
              -s ./out \
              --delete-destination true
